/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickshare;

import java.awt.Container;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash Agarwal
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    static boolean check = false;
    static MainForm mf;
    ReceiveThread rt=null;

    public MainForm() {
        initComponents();
        mf=MainForm.this;
        btnstopreceive.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsend = new javax.swing.JButton();
        btnreceive = new javax.swing.JButton();
        lblmsg = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        btnstopreceive = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsend.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        btnreceive.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnreceive.setText("Receive");
        btnreceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiveActionPerformed(evt);
            }
        });

        lblmsg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblip.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblip.setForeground(new java.awt.Color(51, 51, 255));

        btnstopreceive.setText("Stop Receive");
        btnstopreceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopreceiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblip, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnstopreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnstopreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        SendForm sf = new SendForm();
        sf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnreceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiveActionPerformed
        // TODO add your handling code here:
        btnstopreceive.setEnabled(true);
        try {

            lblmsg.setText("Enter this IP in Sender's IP Box");
            InetAddress ip = InetAddress.getLocalHost();
            lblip.setText(ip.getHostAddress());
            
            rt = new ReceiveThread();
            rt.start();
            btnreceive.setEnabled(false);
            

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnreceiveActionPerformed

    private void btnstopreceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopreceiveActionPerformed
        // TODO add your handling code here:
        btnreceive.setEnabled(true);
        btnstopreceive.setEnabled(false);
        if(rt!=null&&rt.isAlive())
        {
            int i = JOptionPane.showConfirmDialog(null, "Abort Progress", "Are you sure ?", JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                try{
                    rt.releaseResource();
                    rt.stop();
                    lblip.setText("Send or Receive");
                    lblmsg.setText("Quick Share");
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                
            }
        }
    }//GEN-LAST:event_btnstopreceiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JButton btnreceive;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnstopreceive;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lblmsg;
    // End of variables declaration//GEN-END:variables
}
